name: Run Pytest

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DB_USER: postgres
      DB_PASSWORD: postgres

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Pytest
        run: pytest --verbose

      - name: Save test results
        run: |
          echo "test_status=passed" >> test_results.txt
          echo "db_connection_checked=true" >> test_results.txt

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test_results.txt
  
  debug:
    runs-on: ubuntu-latest
    needs: test  # testジョブの完了を待つ
    env:
      DB_USER: postgres
      DB_PASSWORD: postgres

    steps:
      - name: Download test results
        uses: actions/download-artifact@v3
        with:
          name: test-results

      - name: Print DB Info and Test Results
        run: |
          echo "Database User: $DB_USER"
          echo "DB User: $DB_USER"
          echo "--- Test Results ---"
          cat test_results.txt